// Code generated by dbus-codegen-go DO NOT EDIT.
package client

import (
	"context"
	"errors"
	"fmt"
	"github.com/godbus/dbus/v5"
)

// Interface name constants.
const (
	InterfaceDeviceEventListener = "org.a11y.atspi.DeviceEventListener"
)

// NewDeviceEventListener creates and allocates org.a11y.atspi.DeviceEventListener.
func NewDeviceEventListener(object dbus.BusObject) *DeviceEventListener {
	return &DeviceEventListener{object}
}

// DeviceEventListener implements org.a11y.atspi.DeviceEventListener D-Bus interface.
type DeviceEventListener struct {
	object dbus.BusObject
}

// NotifyEvent calls org.a11y.atspi.DeviceEventListener.NotifyEvent method.
//
// Annotations:
//   @org.qtproject.QtDBus.QtTypeName.In0 = QSpiDeviceEvent
func (o *DeviceEventListener) NotifyEvent(ctx context.Context, event struct {
	V0 uint32
	V1 int32
	V2 uint32
	V3 uint32
	V4 int32
	V5 string
	V6 bool
}) (out0 bool, err error) {
	err = o.object.CallWithContext(ctx, InterfaceDeviceEventListener+".NotifyEvent", 0, event).Store(&out0)
	return
}
