// Code generated by dbus-codegen-go DO NOT EDIT.
package server

import (
	"github.com/godbus/dbus/v5"
)

// Interface name constants.
const (
	InterfaceAccessible = "org.a11y.atspi.Accessible"
)

// Accessibleer is org.a11y.atspi.Accessible interface.
type Accessibleer interface {
	// GetChildAtIndex is org.a11y.atspi.Accessible.GetChildAtIndex method.
	GetChildAtIndex(index int32) (out0 struct {
		V0 string
		V1 dbus.ObjectPath
	}, err *dbus.Error)
	// GetChildren is org.a11y.atspi.Accessible.GetChildren method.
	GetChildren() (out0 []struct {
		V0 string
		V1 dbus.ObjectPath
	}, err *dbus.Error)
	// GetIndexInParent is org.a11y.atspi.Accessible.GetIndexInParent method.
	GetIndexInParent() (out0 int32, err *dbus.Error)
	// GetRelationSet is org.a11y.atspi.Accessible.GetRelationSet method.
	GetRelationSet() (out0 []struct {
		V0 uint32
		V1 []struct {
			V0 string
			V1 dbus.ObjectPath
		}
	}, err *dbus.Error)
	// GetRole is org.a11y.atspi.Accessible.GetRole method.
	GetRole() (out0 uint32, err *dbus.Error)
	// GetRoleName is org.a11y.atspi.Accessible.GetRoleName method.
	GetRoleName() (out0 string, err *dbus.Error)
	// GetLocalizedRoleName is org.a11y.atspi.Accessible.GetLocalizedRoleName method.
	GetLocalizedRoleName() (out0 string, err *dbus.Error)
	// GetState is org.a11y.atspi.Accessible.GetState method.
	GetState() (out0 []uint32, err *dbus.Error)
	// GetAttributes is org.a11y.atspi.Accessible.GetAttributes method.
	GetAttributes() (out0 map[string]string, err *dbus.Error)
	// GetApplication is org.a11y.atspi.Accessible.GetApplication method.
	GetApplication() (out0 struct {
		V0 string
		V1 dbus.ObjectPath
	}, err *dbus.Error)
	// GetInterfaces is org.a11y.atspi.Accessible.GetInterfaces method.
	GetInterfaces() (out0 []string, err *dbus.Error)
}

// ExportAccessible exports the given object that implements org.a11y.atspi.Accessible on the bus.
func ExportAccessible(conn *dbus.Conn, path dbus.ObjectPath, v Accessibleer) error {
	return conn.ExportSubtreeMethodTable(map[string]interface{}{
		"GetChildAtIndex":      v.GetChildAtIndex,
		"GetChildren":          v.GetChildren,
		"GetIndexInParent":     v.GetIndexInParent,
		"GetRelationSet":       v.GetRelationSet,
		"GetRole":              v.GetRole,
		"GetRoleName":          v.GetRoleName,
		"GetLocalizedRoleName": v.GetLocalizedRoleName,
		"GetState":             v.GetState,
		"GetAttributes":        v.GetAttributes,
		"GetApplication":       v.GetApplication,
		"GetInterfaces":        v.GetInterfaces,
	}, path, InterfaceAccessible)
}

// UnexportAccessible unexports org.a11y.atspi.Accessible interface on the named path.
func UnexportAccessible(conn *dbus.Conn, path dbus.ObjectPath) error {
	return conn.Export(nil, path, InterfaceAccessible)
}

// UnimplementedAccessible can be embedded to have forward compatible server implementations.
type UnimplementedAccessible struct{}

func (*UnimplementedAccessible) iface() string {
	return InterfaceAccessible
}

func (*UnimplementedAccessible) GetChildAtIndex(index int32) (out0 struct {
	V0 string
	V1 dbus.ObjectPath
}, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetChildren() (out0 []struct {
	V0 string
	V1 dbus.ObjectPath
}, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetIndexInParent() (out0 int32, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetRelationSet() (out0 []struct {
	V0 uint32
	V1 []struct {
		V0 string
		V1 dbus.ObjectPath
	}
}, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetRole() (out0 uint32, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetRoleName() (out0 string, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetLocalizedRoleName() (out0 string, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetState() (out0 []uint32, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetAttributes() (out0 map[string]string, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetApplication() (out0 struct {
	V0 string
	V1 dbus.ObjectPath
}, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAccessible) GetInterfaces() (out0 []string, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}
