// Code generated by dbus-codegen-go DO NOT EDIT.
package server

import (
	"github.com/godbus/dbus/v5"
)

// Interface name constants.
const (
	InterfaceAction = "org.a11y.atspi.Action"
)

// Actioner is org.a11y.atspi.Action interface.
type Actioner interface {
	// GetDescription is org.a11y.atspi.Action.GetDescription method.
	GetDescription(index int32) (out0 string, err *dbus.Error)
	// GetName is org.a11y.atspi.Action.GetName method.
	GetName(index int32) (out0 string, err *dbus.Error)
	// GetLocalizedName is org.a11y.atspi.Action.GetLocalizedName method.
	GetLocalizedName(index int32) (out0 string, err *dbus.Error)
	// GetKeyBinding is org.a11y.atspi.Action.GetKeyBinding method.
	GetKeyBinding(index int32) (out0 string, err *dbus.Error)
	// GetActions is org.a11y.atspi.Action.GetActions method.
	GetActions() (out0 []struct {
		V0 string
		V1 string
		V2 string
	}, err *dbus.Error)
	// DoAction is org.a11y.atspi.Action.DoAction method.
	DoAction(index int32) (out0 bool, err *dbus.Error)
}

// ExportAction exports the given object that implements org.a11y.atspi.Action on the bus.
func ExportAction(conn *dbus.Conn, path dbus.ObjectPath, v Actioner) error {
	return conn.ExportSubtreeMethodTable(map[string]interface{}{
		"GetDescription":   v.GetDescription,
		"GetName":          v.GetName,
		"GetLocalizedName": v.GetLocalizedName,
		"GetKeyBinding":    v.GetKeyBinding,
		"GetActions":       v.GetActions,
		"DoAction":         v.DoAction,
	}, path, InterfaceAction)
}

// UnexportAction unexports org.a11y.atspi.Action interface on the named path.
func UnexportAction(conn *dbus.Conn, path dbus.ObjectPath) error {
	return conn.Export(nil, path, InterfaceAction)
}

// UnimplementedAction can be embedded to have forward compatible server implementations.
type UnimplementedAction struct{}

func (*UnimplementedAction) iface() string {
	return InterfaceAction
}

func (*UnimplementedAction) GetDescription(index int32) (out0 string, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAction) GetName(index int32) (out0 string, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAction) GetLocalizedName(index int32) (out0 string, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAction) GetKeyBinding(index int32) (out0 string, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAction) GetActions() (out0 []struct {
	V0 string
	V1 string
	V2 string
}, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedAction) DoAction(index int32) (out0 bool, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}
