// Code generated by dbus-codegen-go DO NOT EDIT.
package server

import (
	"github.com/godbus/dbus/v5"
)

// Interface name constants.
const (
	InterfaceHyperlink = "org.a11y.atspi.Hyperlink"
)

// Hyperlinker is org.a11y.atspi.Hyperlink interface.
type Hyperlinker interface {
	// GetObject is org.a11y.atspi.Hyperlink.GetObject method.
	GetObject(i int32) (out0 struct {
		V0 string
		V1 dbus.ObjectPath
	}, err *dbus.Error)
	// GetURI is org.a11y.atspi.Hyperlink.GetURI method.
	GetURI(i int32) (out0 string, err *dbus.Error)
	// IsValid is org.a11y.atspi.Hyperlink.IsValid method.
	IsValid() (out0 bool, err *dbus.Error)
}

// ExportHyperlink exports the given object that implements org.a11y.atspi.Hyperlink on the bus.
func ExportHyperlink(conn *dbus.Conn, path dbus.ObjectPath, v Hyperlinker) error {
	return conn.ExportSubtreeMethodTable(map[string]interface{}{
		"GetObject": v.GetObject,
		"GetURI":    v.GetURI,
		"IsValid":   v.IsValid,
	}, path, InterfaceHyperlink)
}

// UnexportHyperlink unexports org.a11y.atspi.Hyperlink interface on the named path.
func UnexportHyperlink(conn *dbus.Conn, path dbus.ObjectPath) error {
	return conn.Export(nil, path, InterfaceHyperlink)
}

// UnimplementedHyperlink can be embedded to have forward compatible server implementations.
type UnimplementedHyperlink struct{}

func (*UnimplementedHyperlink) iface() string {
	return InterfaceHyperlink
}

func (*UnimplementedHyperlink) GetObject(i int32) (out0 struct {
	V0 string
	V1 dbus.ObjectPath
}, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedHyperlink) GetURI(i int32) (out0 string, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedHyperlink) IsValid() (out0 bool, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}
