// Code generated by dbus-codegen-go DO NOT EDIT.
package server

import (
	"github.com/godbus/dbus/v5"
)

// Interface name constants.
const (
	InterfaceHypertext = "org.a11y.atspi.Hypertext"
)

// Hypertexter is org.a11y.atspi.Hypertext interface.
type Hypertexter interface {
	// GetNLinks is org.a11y.atspi.Hypertext.GetNLinks method.
	GetNLinks() (out0 int32, err *dbus.Error)
	// GetLink is org.a11y.atspi.Hypertext.GetLink method.
	GetLink(linkIndex int32) (out0 struct {
		V0 string
		V1 dbus.ObjectPath
	}, err *dbus.Error)
	// GetLinkIndex is org.a11y.atspi.Hypertext.GetLinkIndex method.
	GetLinkIndex(characterIndex int32) (out0 int32, err *dbus.Error)
}

// ExportHypertext exports the given object that implements org.a11y.atspi.Hypertext on the bus.
func ExportHypertext(conn *dbus.Conn, path dbus.ObjectPath, v Hypertexter) error {
	return conn.ExportSubtreeMethodTable(map[string]interface{}{
		"GetNLinks":    v.GetNLinks,
		"GetLink":      v.GetLink,
		"GetLinkIndex": v.GetLinkIndex,
	}, path, InterfaceHypertext)
}

// UnexportHypertext unexports org.a11y.atspi.Hypertext interface on the named path.
func UnexportHypertext(conn *dbus.Conn, path dbus.ObjectPath) error {
	return conn.Export(nil, path, InterfaceHypertext)
}

// UnimplementedHypertext can be embedded to have forward compatible server implementations.
type UnimplementedHypertext struct{}

func (*UnimplementedHypertext) iface() string {
	return InterfaceHypertext
}

func (*UnimplementedHypertext) GetNLinks() (out0 int32, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedHypertext) GetLink(linkIndex int32) (out0 struct {
	V0 string
	V1 dbus.ObjectPath
}, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}

func (*UnimplementedHypertext) GetLinkIndex(characterIndex int32) (out0 int32, err *dbus.Error) {
	err = &dbus.ErrMsgUnknownMethod
	return
}
