// Code generated by dbus-codegen-go DO NOT EDIT.
package server

import (
	"github.com/godbus/dbus/v5"
)

// Interface name constants.
const (
	InterfaceValue = "org.a11y.atspi.Value"
)

// Valueer is org.a11y.atspi.Value interface.
type Valueer interface {
}

// ExportValue exports the given object that implements org.a11y.atspi.Value on the bus.
func ExportValue(conn *dbus.Conn, path dbus.ObjectPath, v Valueer) error {
	return conn.ExportSubtreeMethodTable(map[string]interface{}{}, path, InterfaceValue)
}

// UnexportValue unexports org.a11y.atspi.Value interface on the named path.
func UnexportValue(conn *dbus.Conn, path dbus.ObjectPath) error {
	return conn.Export(nil, path, InterfaceValue)
}

// UnimplementedValue can be embedded to have forward compatible server implementations.
type UnimplementedValue struct{}

func (*UnimplementedValue) iface() string {
	return InterfaceValue
}
